server:
  port: 8760
config:
  server:
    instance:
      hostname: configserver.ssii.com
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitea.ssii.com/rdp/spring-cloud-k8s.git
          searchPaths: config-repo
        native:
          searchLocations: ../config-repo
  profiles:
    active: native

eureka:
  instance:
    hostname: eureka.ssii.com
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}\:8761/eureka/